### ISSUE TITLE
`OriginalImageResultItem` Links to 404 Page

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/capture-vision-docs-js#26]
OriginalImageResultItem does not lead to any page under the CVR API reference page.

Ref: https://www.dynamsoft.com/capture-vision/docs/web/programming/javascript/api-reference/capture-vision-router/captured-result-receiver.html?product=dbr&ver=latest&dbr=latest&lang=javascript#onoriginalimageresultreceived

Should link to https://www.dynamsoft.com/capture-vision/docs/mobile/programming/android/api-reference/core/basic-structures/original-image-result-item.html

**Comment by Tom-Dynamsoft** [comment]
Fixed. OriginalImageResultItem  linked to https://www.dynamsoft.com/capture-vision/docs/web/programming/javascript/api-reference/core/basic-structures/original-image-result-item.html
